openapi: 3.0.3
info:
  title: Your API
  version: 1.0.0
  description: Your project description
paths:
  /api/generate-thread/:
    post:
      operationId: generate_thread_create
      tags:
      - generate-thread
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/YouTubeToTwitterInputRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/YouTubeToTwitterInputRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/YouTubeToTwitterInputRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YouTubeToTwitterInput'
          description: ''
components:
  schemas:
    YouTubeToTwitterInput:
      type: object
      properties:
        youtube_url:
          type: string
          format: uri
      required:
      - youtube_url
    YouTubeToTwitterInputRequest:
      type: object
      properties:
        youtube_url:
          type: string
          format: uri
          minLength: 1
      required:
      - youtube_url
