# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: adr-axs5pmspipgz5k7qdqjo9nswtc.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
# from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# _runtime_version.ValidateProtobufRuntimeVersion(
#     _runtime_version.Domain.PUBLIC,
#     5,
#     28,
#     3,
#     '',
#     'adr-axs5pmspipgz5k7qdqjo9nswtc.proto'
# )
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$adr-axs5pmspipgz5k7qdqjo9nswtc.proto\x12\x03\x61\x64r\"\x18\n\x0bInputString\x12\t\n\x01s\x18\x01 \x01(\t\"Z\n\x0e\x41\x44RReturnFloat\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x64\x18\x02 \x01(\x02\x12\t\n\x01r\x18\x03 \x01(\x02\x12\x0b\n\x03img\x18\x04 \x01(\t\x12\x0c\n\x04numr\x18\x05 \x01(\x05\x12\x0c\n\x04numc\x18\x06 \x01(\x05\x32\x43\n\x11ServiceDefinition\x12.\n\x03\x61\x64r\x12\x10.adr.InputString\x1a\x13.adr.ADRReturnFloat\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adr_axs5pmspipgz5k7qdqjo9nswtc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTSTRING']._serialized_start=45
  _globals['_INPUTSTRING']._serialized_end=69
  _globals['_ADRRETURNFLOAT']._serialized_start=71
  _globals['_ADRRETURNFLOAT']._serialized_end=161
  _globals['_SERVICEDEFINITION']._serialized_start=163
  _globals['_SERVICEDEFINITION']._serialized_end=230
# @@protoc_insertion_point(module_scope)
