[theme]
primaryColor = "#1f77b4"  # Primary color of the app
backgroundColor = "#0e1117"  # Dark background color
secondaryBackgroundColor = "#262730"  # Slightly lighter dark color
textColor = "#ffffff"  # White text color
