[general]
API_KEY = "EQq22/s2o9EaXKTJ8EFbKxfoTTuW"
xAPI_URL = "https://djangoapp.vveeq17939eno.us-east-2.cs.amazonlightsail.com/snet/energy-forecast/"
API_URL = "http://127.0.0.1:8000/snet/energy-forecast/"